using System.Collections.Generic;

namespace DMMusic
{
    internal sealed class ModConfig
    {
        public bool EnableDebugLogging { get; set; } = true;
        public bool ShowSuggestionsAlways { get; set; } = true;

        // 0 = never allow vanilla (always replace when possible)
        // 100 = always allow vanilla (never replace, even if configured)
        public int VanillaInsteadPercent { get; set; } = 0;

        // Disabled replacement entries (dynamic list managed by GMCM page).
        // Each entry is an ID generated by MusicManager.BuildReplacementId(...)
        public HashSet<string> DisabledReplacementIds { get; set; } = new(System.StringComparer.OrdinalIgnoreCase);
    }
}
